Made the `getSin` and `getCos` methods no longer static
because otherwise it says:
`warning: 'const int8_t getSin(uint8_t)' declared 'static' but never defined`
and
`<artificial>:(.text+0x2044): undefined reference to `getSin(unsigned char)'`

(also with a `defined but not declared`, or something on the definition of the function)